### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by djfaizp** [navetacandra/deepinfra#1]
is this project finished?
how to use it ? i want open ai like base url

**Comment by navetacandra** [comment]
not yet, it still under development

**Comment by navetacandra** [comment]
Now package is available on [npmjs.com](https://www.npmjs.com/package/@navetacandra/deepinfra)

**Comment by djfaizp** [comment]
bro can you make changes in 
`https://github.com/LLM-Red-Team/deepseek-free-api.git`
and make it for deepinfra

**Comment by navetacandra** [comment]
> bro can you make changes in `https://github.com/LLM-Red-Team/deepseek-free-api.git` and make it for deepinfra

I don't think i can do that. And I think `https://github.com/LLM-Red-Team/deepseek-free-api.git` only provide for deepseek API, and the name of repo is already describe it "deepseek-free-api"

**Comment by djfaizp** [comment]
i know that bro it's for deepseek only but can you fork and apply changes to make it compatible for deepinfra 
somebudy have made for cli but it's not wrapper for api
`https://github.com/SreejanPersonal/JARVIS-AGI/blob/91ed51fc4d61b4b4fc4a8b6c6f92ad7f90faf0c9/BRAIN/AI/TEXT/API/deepInfra_TEXT.py`
python wrapper but I'm not able to make it in `https://github.com/LLM-Red-Team/deepseek-free-api.git`

**Comment by navetacandra** [comment]
if you need for NodeJS, just simply cl

**Comment by navetacandra** [comment]
If you need for NodeJS, just simply fork my repo or install it using npm.
If you need for Python, just simply copy the code from https://github.com/SreejanPersonal/JARVIS-AGI/blob/91ed51fc4d61b4b4fc4a8b6c6f92ad7f90faf0c9/BRAIN/AI/TEXT/API/deepInfra_TEXT like you mention it

**Comment by djfaizp** [comment]
> If you need for NodeJS, just simply fork my repo or install it using npm. If you need for Python, just simply copy the code from https://github.com/SreejanPersonal/JARVIS-AGI/blob/91ed51fc4d61b4b4fc4a8b6c6f92ad7f90faf0c9/BRAIN/AI/TEXT/API/deepInfra_TEXT like you mention it

it doesn't matter what i need is openai compatible api is it support it ? 
if yes how to use it can you please explain?

**Comment by navetacandra** [comment]
i don't get what you mean, can you give references?
or you can just simply use the package with reading example usage

**Comment by djfaizp** [comment]
bro, i want to use it inside **[openweb](https://docs.openwebui.com/)** ui how to do that ?

**Comment by navetacandra** [comment]
I think you can just create your own backend API from an available package, and modify the Open-WebUI client to use from your API.
